import { existsSync, readFileSync, writeFileSync } from 'node:fs'

function readLocalEnv() {
  if (!existsSync('.env.local')) return {}
  return Object.fromEntries(
    readFileSync('.env.local', 'utf8')
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#') && line.includes('='))
      .map((line) => {
        const [key, ...value] = line.split('=')
        return [key, value.join('=')]
      }),
  )
}

const localEnv = readLocalEnv()
const getEnv = (key) => process.env[key] || localEnv[key] || ''

const config = {
  apiKey: getEnv('VITE_FB_API_KEY'),
  authDomain: getEnv('VITE_FB_AUTH_DOMAIN'),
  projectId: getEnv('VITE_FB_PROJECT_ID'),
  storageBucket: getEnv('VITE_FB_STORAGE_BUCKET'),
  messagingSenderId: getEnv('VITE_FB_MSG_SENDER_ID'),
  appId: getEnv('VITE_FB_APP_ID'),
}

const missing = Object.entries(config)
  .filter(([, value]) => !value)
  .map(([key]) => key)

if (missing.length > 0) {
  console.warn(`[fcm-sw] Missing Firebase env values: ${missing.join(', ')}`)
}

const content = `/* generated by scripts/write-fcm-sw.mjs */
importScripts('https://www.gstatic.com/firebasejs/10.13.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.13.0/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(config, null, 2)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const notification = payload.notification || {};
  const title = notification.title || 'DietQuest reminder';
  const options = {
    body: notification.body || 'Open DietQuest to log your progress.',
    icon: '/icons/icon-192.png',
    badge: '/icons/icon-192.png',
    data: {
      url: payload.fcmOptions?.link || payload.data?.url || '/',
    },
  };

  self.registration.showNotification(title, options);
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const targetUrl = new URL(event.notification.data?.url || '/', self.location.origin).href;
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if ('focus' in client) {
          client.navigate(targetUrl);
          return client.focus();
        }
      }
      return clients.openWindow(targetUrl);
    }),
  );
});
`

writeFileSync('public/firebase-messaging-sw.js', content, 'utf8')
console.log('[fcm-sw] Wrote public/firebase-messaging-sw.js')
